server:
  port: 8888

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.186.89:3306/interface_flask_server
    username: root
    password: xulei123

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*